name: Publish to VS Code Marketplace and Open VSX

on:
  workflow_dispatch:

jobs:
  publish-vsix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run package:prepare
      - name: Publish to Open VSX
        uses: HaaLeo/publish-vscode-extension@v2
        id: publishToOpenVSX
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          packagePath: packages/extension
      - name: Publish to VS Code Marketplace
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
          extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
          registryUrl: https://marketplace.visualstudio.com/
      
      